name: cidcCheck

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: oracle

      - name: Build Maven
        run: mvn -B package --file pom.xml

        
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: uploadjar
          path: target/*.jar

  test:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: uploadjar
          path: target

      - name: Test .jar file
        run: java -jar target/*.jar
  
   

  
   
  
